### ISSUE TITLE
Wiki page link missleading

### ISSUE THREAD

**Issue by Dehir** [sergeygarnov/Rocksmith-Custom-Realtone-Cable#2]
The wiki link page for http://s.click.aliexpress.com/e/qrnMVbE Is missleading.

I have this cheap chinese usb-1/4" guitar sound card with similar casing (Behringer cheap copy) and it doesnt have CM108.

It has PCM2902 which is Texas instruments chip. Which Product/Vendor id cannot be modified by dropping Product/Vendor id via EEPROM. (The id's should be able to changed. But cost is fortune and needs to be done by TI) So no easy way hacking it though.

So i think wiki page should be upgraded to point something closer with CM108 hardware. As people tend to be stupid sometimes and buy anything that looks close enough.

**Comment by fluffyanvil** [comment]
Hi!
Thanks for your attention! Fixed.
