### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by chendricks16** [sergeygarnov/Rocksmith-Custom-Realtone-Cable#3]
Its unclear how you plan on using your eeprom chip, you state "Replace EEPROM chips in usb guitar link and new one!" I assume you are referring too the usb sound card from earlier but that sound card doesn't have a 93C46 on it that I can see in the picture. Anyway if you could clear that up that would be awesome thanks! Also the links to the 93C46 don't work anymore, this is a super interesting post I'm really interested in doing this let me know the details. Thanks

**Comment by fluffyanvil** [comment]
Hi! If your sound card has not 93C46 you can solder it like in schematic [click](https://github.com/fluffyanvil/Rocksmith-Diy-Realtone-Cable/blob/master/IMG_0008-e1416384149439-800x500.png)

**Comment by fluffyanvil** [comment]
wiki updated
