### ISSUE TITLE
running the sketch

### ISSUE THREAD

**Issue by prostealth** [sergeygarnov/Rocksmith-Custom-Realtone-Cable#4]
im new with arduino.
how to run the sketch?
is it just connect the eeprom then power the arduino or something else?

**Comment by fluffyanvil** [comment]
> im new with arduino.
> how to run the sketch?
> is it just connect the eeprom then power the arduino or something else?

hi, you need ArduinoIDE if you new and compile and load scetch into board with connected eeprom

**Comment by prostealth** [comment]
and what will i do after upload the sketch?
is it fine if i turn off the arduino and take the eeprom then install it to the soundcard?

**Comment by fluffyanvil** [comment]
> and what will i do after upload the sketch?
> is it fine if i turn off the arduino and take the eeprom then install it to the soundcard?

yep, after flashing eeprom you will diconnect it from arduino and connect to sound card and try your cable

**Comment by prostealth** [comment]
thank you...
its clear now..

**Comment by fluffyanvil** [comment]
Welcome

чт, 3 окт. 2019 г., 16:48 prostealth <notifications@github.com>:
